# Generated by Django 5.0.1 on 2024-02-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='researchData',
        ),
    ]
