# Generated by Django 5.0.1 on 2024-02-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketinsight',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketinsight',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='marketinsight',
            name='impact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='marketinsight',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marketinsight',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='insight',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='pestle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='relevance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketinsight',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
